############################################################
# Debian Jessie 
############################################################

FROM lburgazzoli/debian-jessie
MAINTAINER lburgazzoli

RUN \
    apt-get install --no-install-recommends -y \
        build-essential
    && rm -rf /var/lib/apt/lists/*
