
FROM lburgazzoli/fedora:25
MAINTAINER lburgazzoli

ARG DOCKER_USER
ARG DOCKER_USER_GID
ARG DOCKER_USER_UID

ENV DOCKER_USER_HOME /home/$DOCKER_USER
ENV HOME             $DOCKER_USER_HOME

RUN \
    dnf install dnf-plugins-core  -y \
    && dnf config-manager --add-repo https://repo.skype.com/data/skype-stable.repo \
    && dnf install skypeforlinux -y \
    && dnf clean all

WORKDIR $DOCKER_USER_HOME
USER $DOCKER_USER
CMD [ "/usr/share/skypeforlinux/skypeforlinux", "--executed-from=$HOME" ]
